config/routes.rb
Rails.application.routes.draw do
	root "currencies#show", id: "bitcoin"

	resources :currencies, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  validates :date, presence: true
  validates :currency_type, presence: true

  enum currency_type: [:bitcoin, :ethereum, :nasdaq]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
require "#{Rails.root}/lib/currencies/currency_client.rb"

class CurrenciesController < ApplicationController

  def show
    @currencies = params[:id] ? params[:id].downcase : ''
    case @currencies
    when  !Currency.currency_types.include?(@currencies) 
      @currencies = {}
    else
      @currencies = set_currencies(@currencies)
    end
  end

private

  def set_currencies(currency_type)
    @currencies = Currency.where(currency_type: Currency.currency_types["#{currency_type}"])
    @currencies.inject({}) do |new_element, current_element|
      date = current_element.date
      value = current_element.value
      new_element[date] = value
      new_element
    end
  end


end

class CurrenciesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/currencies/show.html.erb
<div class="page-header">
  <h1>Values of CryptoCurrencies</h1>
</div>
<% if params[:id] %>
  <h3> Graph of <%= link_to("#{params[:id]}", "https://en.wikipedia.org/wiki/#{params[:id]}") %>: </h3>
<% else %>
  <h3> Choose a currency please: </h3>
<% end %>

<%= line_chart @currencies %>


<div class="btn-toolbar" style="display: flex; margin-top: 15px;"> 
  <div style="margin: auto;"> 
    <a class="btn btn-success" href=<%= currency_path('Bitcoin') %> role="button">Bitcoin</a>
    <a class="btn btn-success" href=<%= currency_path('Ethereum') %> role="button">Ethereum</a>
    <a class="btn btn-success" href=<%= currency_path('Nasdaq') %> role="button">Nasdaq</a>

  </div>
</div>

app/views/graphs/show.html.erb
<div class="page-header">
	<h1>Values of CryptoCurrencies</h1>
</div>
<% if params[:id] %>
		<h3> Graph of <%= link_to("#{params[:id]}", "https://en.wikipedia.org/wiki/#{params[:id]}") %> </h3>
<% else %>
		<h3> Choose a currency please: </h3>
<% end %>

<div class="btn-toolbar"> 
	<a class="btn btn-success" href=<%= graph_path('Bitcoin') %> role="button">Bitcoin</a>
	<a class="btn btn-success" href=<%= graph_path('Ethereum') %> role="button">Ethereum</a>
	<a class="btn btn-success" href=<%= graph_path('Nasdaq') %> role="button">Nasdaq</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <%#
        Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
      https://github.com/calebthompson/title#usage
    %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %> jumbotron vertical-center">
    <%= render "javascript" %>
    <div class="container">
      <%= yield %>
    </div>  
    <%= render "css_overrides" %>
  </body>
</html>